name: Build Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package extension
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bq-cost-estimator
          path: bq-cost-estimator.zip
